### ISSUE TITLE
[BUG] KeyNotFoundException

### ISSUE THREAD

**Issue by GamerInspired** [TeamPorcupine/ProjectPorcupine#758] opened 2016-08-24 18:11 UTC
So I started up the lastest build only to find after a while the error KeyNotFoundException appeared. It also seemed to cause the fps to drop to rock bottom.

![ss 2016-08-24 at 07 07 41](https://cloud.githubusercontent.com/assets/8201304/17942254/883c3f58-6a2e-11e6-9d59-83118d897e99.png)

**Comment by NogginBops** [comment] 2016-08-24 18:21
You left out the important part... the callstack.

**Comment by racerand** [comment] 2016-08-24 18:33
It's the metal smelter, have the same problem, from Parameter.cs: 62

**Comment by koosemose** [comment] 2016-08-24 18:39
Yep, I didn't account for some of the Lua scripts (smelter, and some temperature stuff I think) referencing nonexistent parameters, and only creating them when needed. PR #746 is in the works to fix the issue.

**Comment by GamerInspired** [comment] 2016-08-24 18:48
callstack?

**Comment by mikejbrown** [comment] 2016-08-24 19:11
duplicate of #725

**Comment by NogginBops** [comment] 2016-08-24 19:26
@GamerInspired This is the callstack. The part that tells you where the error occurred.

![image](https://cloud.githubusercontent.com/assets/3778357/17944759/5afb7276-6a41-11e6-8184-073a9722a99c.png)

**Comment by GamerInspired** [comment] 2016-08-24 21:35
Ah that's what that's called, will include next time I post an issues that needs it. Also had it minimised (not hidden just made smaller) so forgot about it.

**Comment by mikejbrown** [comment] 2016-08-25 07:53
Fixed by #746. Should be closed.

**Comment by GamerInspired** [comment] 2016-08-25 09:05
If no one can recreate this then please could a gatekeeper close this.

(I don't like closing issues unless I've tested it but if a gatekeeper has tested it and it's fine then they can close it)

**Comment by Mizipzor** [comment] 2016-08-25 19:30
If it cant be recreated its better to close. If the bug remains a new one will be created. :)

**Closed by Mizipzor** 2016-08-25 19:30 UTC
