### ISSUE TITLE
Multi-character optimization

### ISSUE THREAD

**Issue by ComputerOverlord** [TeamPorcupine/ProjectPorcupine#331] opened 2016-08-19 23:29 UTC
We know from #270 #253 that many characters slows down the game

**Comment by kd7uiy** [comment] 2016-08-19 23:41
Some of this is log spam, which will be reduced when my latest PR gets pulled in to the fray. That won't fix all of it, unfortunately. I think pathfinding is the major source of slowdown, in particular the fact that it seems to be re-done every turn. There's an issue report somewhere here about that.

Bottom line, this is closely related to the following:

https://github.com/TeamPorcupine/ProjectPorcupine/pull/329

https://github.com/TeamPorcupine/ProjectPorcupine/issues/246

**Comment by henninglive** [comment] 2016-08-19 23:42
Maybe disable auto spawning of new characters for now.

**Comment by koosemose** [comment] 2016-08-19 23:52
Yeah PR #250 fixes one of the major causes of this, though until quill is able to get a team that can accept PRs it may take a bit before it comes to his attention and is accepted.

**Comment by relinu** [comment] 2016-08-19 23:55
I will limit the amount of repeats a gameevent can have

**Comment by kd7uiy** [comment] 2016-08-19 23:58
I just pinged quill to get him to prioritize #250 , so let's hope that works. It might help if others join in that? Also, we should prioritize the various logspam ones, which will help.

Finally, the maximum number of characters should probably be re-thought, or at least, how often they spawn.

**Comment by koosemose** [comment] 2016-08-20 00:20
#250 has been committed, take a look to see if that fixes, or at least reduces the issues. My GitHub Desktop is having fits over some files so I can't at the moment.

**Comment by kd7uiy** [comment] 2016-08-20 00:24
Sadly I still see lots of log spam... Sigh. Just the A* pathfinding, but...

**Comment by kd7uiy** [comment] 2016-08-20 00:31
Confirmed the reduced log spam!

**Comment by koosemose** [comment] 2016-08-20 00:42
Well, it's better than it was, but there's still a massive slowdown anytime a long-distance pathfinding is done, which is going to happen more often the more characters there are. Pathfinding code certainly needs optimized.

**Comment by vogonistic** [comment] 2016-08-24 17:12
There has been several improvements for this, but it's going to be an ongoing project. I suggest we add issues for specific things that slows the characters down so we can have a criteria to finish issues.

**Closed by vogonistic** 2016-08-24 17:12 UTC
