### ISSUE TITLE
Furniture building broken

### ISSUE THREAD

**Issue by abackwood** [TeamPorcupine/ProjectPorcupine#1024] opened 2016-08-29 15:00 UTC
Since commit #968 building new furniture is broken for me.

Building the first furniture works fine. Then the second furniture is either not built at all or insta-built (despite dev mode being off). In my own PR I also get all atmospheres being set to NaN.

**Comment by MANDAL0R3** [comment] 2016-08-29 15:09
I can confirm that the bug was happening before #968 was merged. My PR #1012 was made before his got merged and mine is sitting at 10 commits behind the upstream.

**Comment by MANDAL0R3** [comment] 2016-08-29 15:54
I currently have a lead to where the bug originated from but im still looking into it. I assigned a random number to the Job class and i put a break point on OnJobCompleted(this) in the Job class. After placing two mining drones, both of there random number was 480.6847f. My lead is the PrototypeManager, because in the BuildModeController i put a debug log after j = PrototypeManager.FurnitureJob.GetPrototype(furnitureType); to show me what the random number is and its the same.

**Comment by MANDAL0R3** [comment] 2016-08-29 15:57
OK i was right, the culprit is the PrototypeManager. When getting a job for the furniture it never returned a clone. I'm going to put a PR to fix this bug.

**Comment by vogonistic** [comment] 2016-08-29 18:19
@MANDAL0R3 Make sure you put in `fixes #1024` in the PR's description.

**Closed** 2016-08-29 19:02 UTC
Labels: bug
