### ISSUE TITLE
[LOW PRIORITY] Trading system

### ISSUE THREAD

**Issue by ComputerOverlord** [TeamPorcupine/ProjectPorcupine#332] opened 2016-08-19 23:47 UTC
You get KR from completing missions (you start with a KR Distribution Client furniture) you use it to buy stuff (but you can't sell stuff) and You can hack for more credits. Let me make a list.

- [ ] Add KR
- [ ] Add Hacker Terminal
- [ ] Add KRDC

**Comment by mikejbrown** [comment] 2016-08-31 15:57
This has been superseded by the trading system currently [WIP], yes?

**Comment by sboigelot** [comment] 2016-09-02 11:19
I think this is a parallel idea from @ComputerOverlord (more like a different quest/reward idea). It could still be created if he comes back to the discussion and start implementing or describing it, but we have only few information about it.

We can probably close this issue for now.

**Comment by sboigelot** [comment] 2016-09-02 23:14
This is a duplicate of #88

**Closed** 2016-09-03 03:00 UTC
