### ISSUE TITLE
Log Spam and Practices

### ISSUE THREAD

**Issue by bjubes** [TeamPorcupine/ProjectPorcupine#94] opened 2016-08-17 20:15 UTC
While it is very much encouraged to spam the log to your hearts content while testing, there should be some general guidelines on what debug messages should be allowed to be kept in a final PR. I am currently removing the more spammy ones to prevent lag and to find my own messages in the mix, but there should definitely be some written rules about this in either the CONTRIBUTING file or somewhere more fitting.

**Comment by NogginBops** [comment] 2016-08-17 20:16
I agree we need some kind of standard for this!

**Comment by emilkris33** [comment] 2016-08-17 20:19
I general i think that all debug statements that has a chance of running fine should be commented out or deleted. And you should only leave debug statements that definitively indicate something has gone wrong in.

**Comment by bjubes** [comment] 2016-08-17 20:30
Agree @emilkris33. Maybe in the future we could have a custom log with log channels that you could toggle on and off, so that if i'm working with the job system i can turn the job channel on and get only the relevant debug info i need. However that would be beyond impractical now, so a "delete when you don't need it anymore" policy the easiest solution IMO

**Comment by emilkris33** [comment] 2016-08-17 20:33
@bjubes "delete when you don't need it anymore" and more importantly "delete before making a pull request". You might still need it for working on your next thing, but that does not mean everybody else needs it when working on their thing.

**Comment by lameox** [comment] 2016-08-18 10:40
I suggest we facilitate some Compiler Flags. Something like a 
'''
#if VerboseOutput
            Debug.Log("Some Log Message");
#endif
'''
snippet would be great. This way we could just turn those Debug Messages off and on with a compilation Flag. It might also be useful to define our own dedicated logging class that is used instead of Debug.Log. That way we can easily extend our logging mechanisms in the Future. For now it could just mirror the Debug class' Logging methods and call them, wrapped in the above mentioned compiler flag, but in the future we might want to log to a file, sqliteDB or something else along those lines.

**Comment by Mizipzor** [comment] 2016-08-18 11:03
A much better way to do that is to create our own logger class that wraps the unity logging. You already log to a "level" (error, warning, verbose), so we could add a setting and only show that level and above. Sometimes you need to readd the verbose logging when you debug something which is difficult if the lines have been removed. Adding a setting scales much better.

**Comment by lameox** [comment] 2016-08-18 11:06
We should keep the levels for sure. But i think in a release build we should not have any calls to Debug.Log at all. This is best accomplished with a Preprocessor flag around our Debug.Log call(s).

In doing so we will also have a slightly smaller, slightly more performant binary as the Debug.Log calls wont even be compiled.

**Comment by Mizipzor** [comment] 2016-08-18 11:18
In a release build you could disable all the logging with the same setting I suggest. In my experience preprocessor flags always causes more problems than they solve. People write code and doesn't test in release. And then when somebody _do_ run in release all sorts of weird stuff happen because there was a typo in one of the preprocessor flags. The gain in filesize and execution speed is completely negligible. In fact, where I work there's a rule against using them. And if you do, you better have a good reason when it's time for code review.

**Comment by NogginBops** [comment] 2016-08-18 11:20
@Mizipzor I like the custom logger idea. Seen a lot of teams do the same. I mean unity has support for custom windows so it's not really that hard to do.

**Comment by lameox** [comment] 2016-08-18 11:30
@Mizipzor well i guess you have a point. Is there an automated way to disable the logging in release or do we have to do that by hand before compiling for release? That was my main concern, as people might forget to do so.

**Comment by NogginBops** [comment] 2016-08-18 11:32
If nothing else there could be a precompiler flag in the custom debugger to not accept log messages.

**Comment by Mizipzor** [comment] 2016-08-18 12:00
@NogginBops yes, if we absolutely cant avoid the preprocessor flags then it's best to aim at having as few as possible.

**Comment by lameox** [comment] 2016-08-18 12:03
@Mizipzor @NogginBops yeah that was my thought as well. We should have the wrapped methods of Debug and only in there have the preprocessor flags. 
We might also consider writing a code analyzer down the line that checks new pull requests for uses of Debug's log functions and automatically declines the request with an appropriate comment. this way we could ensure that everything that needs to hit a log file is funneled through our wrapper.

**Comment by OzieGamma** [comment] 2016-08-18 19:19
C# has a neat feature `[ConditionalAttribute("DEBUG")]`. Put that above a method and the method calls will only be included in debug. I propsed to add that to PR #185

**Comment by Mizipzor** [comment] 2016-08-18 19:22
@OzieGamma The same concern was raised in the PR. My argument against it is that sometimes you want verbose logging in a release build. Say, if someone has a bug that they can reproduce with verbose logging. It should obviously not be enabled by default, but there's no reason taking extra steps to remove that feature.

**Comment by lameox** [comment] 2016-08-18 19:26
also i think we should not exclude a whole method. my idea was  something along the lines of the following code
```csharp
class Wrapper
{
    public static void Log(string message)
    {
    #if DEBUG
        Debug.Log(message);
    #endif
        //Other logging mechanisms go here. Think logfile or db.
    }
//same for the other methods
}
```

that way we would only disable a single log output but keep the others. But again this was heavily debated/dislike which caused us to postpone the decision/think about it some more.

**Comment by OzieGamma** [comment] 2016-08-18 19:28
@Mizipzor I think that using ` [ConditionalAttribute("DEBUG")] ` is a good middleground:

- If you need to debug something in a release build for whatever reason, you can just comment the attribute out in **one** place.
- You don't have the slight performance hit of all the checks against the logging level.

If performance doesn't matter, I would go for not having the attribute.

**Comment by OzieGamma** [comment] 2016-08-18 19:29
@lameox That's a very bad idea. It will grow out of control and become very hard to know what is turned on or off.

**Comment by lameox** [comment] 2016-08-18 19:36
@OzieGamma isn't that attribute something you decorate a Method definition with? If not then i misunderstood the intended use.

Yes thats why both me and @Mizipzor said we are not going with that solution. I just wanted to show you what was proposed so far ;)

**Comment by OzieGamma** [comment] 2016-08-18 19:47
@lameox Yes and the use is in the custom logger #185 but @Mizipzor has good reasons not to use it.

Ah ok.

**Comment by Mizipzor** [comment] 2016-08-18 20:07
@OzieGamma It's not just a matter of removing that line. Or, rather, the problem is that it requires the binaries to be rebuilt. My specific use case, or argument, was a user that had a bug that he could reliably reproduce. And its easier for the user to change a setting rather than download some special version of the application.

**Comment by lameox** [comment] 2016-08-18 20:14
Oh nice, i had not seen #185 go up. So far it looks like a good implementation/solution for our problem and definitely beats any solutions relying on compiler flags. for me in my initial suggestion that was more of a quick and dirty solution as i did not think we would implement a real wrapper this early.
@bjubes i guess you can close this
@Mizipzor would you say implementing a code analyzer like i suggested above would be a good idea for the future?

**Comment by Mizipzor** [comment] 2016-08-18 20:20
@lameox your intention with a static code analyzer is good, but from experience it always more work than its worth. Usually, the ones that bother running the analyzer is usually good enough to get it right the first time anyway. I think this is something thats best left the regular code reviews. Look through the code, do they log, and how.

This also doesnt address the scenario that maybe sometimes you _want_ to bypass my logging filter. Maybe its something so important that it absolutely have to be logged, always.

**Comment by lameox** [comment] 2016-08-18 20:30
My thought was using the new Roslyn tools. That really makes the task a simple one and we could just implement it as a unit test that would fail in our CI setup thus failing the PR in question. I think your second concern can easily be done by just calling the Debug Log always as the first thing in our wrapper. that way we do effectively the same thing

**Comment by Mizipzor** [comment] 2016-08-18 21:00
Always calling Debug.Log would defeat the purpose of the custom logger, which was filtering.

**Comment by lameox** [comment] 2016-08-18 21:12
Yeah but if we have a really urgent log entry we can just call the correct wrapped function and it should not make a difference

**Comment by OzieGamma** [comment] 2016-08-18 21:55
@lameox does unity already support Roslyn ?

**Comment by lameox** [comment] 2016-08-18 22:09
@OzieGamma I dont know, but this tool would not need to reside in unity. all it has to do is inspect the cs files contained in the unity project wich is easily doable. Then you have it return some meaningful exception and integrate it as part of your test process.

**Comment by vogonistic** [comment] 2016-08-22 04:00
Is this still an ongoing discussion or are we ok with what has been merged?

**Comment by Mizipzor** [comment] 2016-08-22 12:14
Four days of inactivity is an eternity in this project. ^^ I think this can be closed.

**Comment by vogonistic** [comment] 2016-08-24 15:19
Warning shot was ignored, closing.

**Closed by vogonistic** 2016-08-24 15:19 UTC
