### ISSUE TITLE
Power Cell Press puts cells in walls

### ISSUE THREAD

**Issue by kd7uiy** [TeamPorcupine/ProjectPorcupine#975] opened 2016-08-28 12:18 UTC
![capture](https://cloud.githubusercontent.com/assets/5951269/18033617/ef3e5be8-6cf7-11e6-906f-f545abd17695.PNG)

Not quite sure what the solution for this should be, but this doesn't seem right.

**Comment by Fatalexceptionz** [comment] 2016-08-28 12:58
The Power Cell sprite looks all sorts of broken too...

**Comment by Grenkin1988** [comment] 2016-08-28 13:57
Same issue - metal floating near landing pad
![inventory](https://cloud.githubusercontent.com/assets/2979432/18034239/6820be1e-6d40-11e6-86e9-6dc5457d25d2.PNG)

**Comment by kd7uiy** [comment] 2016-08-28 14:01
I was just about to include something similar;-) Nice work!

**Comment by sboigelot** [comment] 2016-08-28 20:08
The metal hanging out of the landing pad is still a test feature, we shouldn't worry about it. 

#817 (+following PR) will replace this shortly

**Comment by Grenkin1988** [comment] 2016-08-28 20:12
This is because existing solution do not care what is there is spawn point, but it should

**Comment by sboigelot** [comment] 2016-08-28 20:17
Before implementing a solution that care, we should show the player where the job point and spawn points (and all other points) are during the construction or when a furniture is selected

**Comment by MANDAL0R3** [comment] 2016-08-29 05:55
@sboigelot, What do you think about showing the job and spawn point with something like this? 
![idea](https://cloud.githubusercontent.com/assets/12440052/18041964/9d587da6-6d8b-11e6-9704-3b49a3768c54.png)

**Comment by sboigelot** [comment] 2016-08-29 12:45
@MANDAL0R3 it looks great to me

**Comment by MANDAL0R3** [comment] 2016-08-29 13:17
@sboigelot Well if it was supposed to be then its a bug, for me the raw iron is produced where the i put the blue square

**Comment by sboigelot** [comment] 2016-08-29 13:30
@MANDAL0R3 ho yes sorry, my bad, I confused it with the metal smelter, you are totally correct!

**Comment by MANDAL0R3** [comment] 2016-08-29 13:33
@sboigelot, I have been doing math home work all night, i honestly thought that i had gone insane for a minute :D

**Comment by dusho** [comment] 2016-08-30 19:45
so those in/out slots should be checked when placing devices for building, whether there are empty slots (or compatible inventory item placed there already)
There was a discussion on generic factory/device #604 , so it would really make sense to create subclass from Furniture (Factory or Device, ... ) that would contain input and output port positions together with stuff that all processing devices will have

**Comment by Grenkin1988** [comment] 2016-09-06 13:59
9 days old bug is not good :-(

**Comment by dusho** [comment] 2016-09-06 14:11
I can probably fix that with my #1084 , there furniture knows about its input/output slots and during build phase I can check if those slots are free (not allow to build if not)

**Comment by dusho** [comment] 2016-09-12 06:07
machine (workshop) will now not spit out an output if there is no free space (or item can be added to stack)
#1084 is merged to master now, this can be closed

**Comment by koosemose** [comment] 2016-09-18 11:28
Tried to confirm rather or not this was solved, but ran into #1311, in the process, which means the press won't produce anything (since it's not getting both required materials)

**Comment by koosemose** [comment] 2016-09-19 05:54
This has been solved, a now that #1311 I can confirm that it in fact has. Closing.

**Closed by koosemose** 2016-09-19 05:54 UTC
Labels: bug
