### ISSUE TITLE
[Discussion] Just an idea for "multiplayer" mode

### ISSUE THREAD

**Issue by TheAvaren** [TeamPorcupine/ProjectPorcupine#1348] opened 2016-09-16 05:26 UTC
So back in tutorial episode 3 i had an idea but never announced it. i though it would be pretty cool but then i stopped watching when around episode 15 only because i was episode late about when he introduced XML(for some reason i hate it), but the idea was that anything connect to a "another tile" would be a satellite and all connect tile would contain a main transform and anything not connect would float of, for example let say that there is one floor tile connect wing-a to "the-hull" of a spacestation, and if the tile broke it would float away, now this maybe be to complicated but this could also induce multiple satellites and what not also allowing multiple people in one game only player with permission can modify there own satellite, i am a jack of a lot of trade's and if this idea is not understand-ed or is very-understand-ed i can make a small video in adobe AE that describes it more, sorry if this is posted wrongly posted.

**Comment by pderuiter77** [comment] 2016-09-16 06:35
i think adding multiplayer at this time is a bit much to ask. I like the separate floating objects thing, although i do hope you get a chance to get them back together again :)

**Comment by mikejbrown** [comment] 2016-09-16 08:30
Issues is the right place for posting an idea like this.

I agree that it is too early to build multiplayer into the game. Making disconnected bits float away might be doable soonish though.

**Comment by bjubes** [comment] 2016-09-16 15:17
duplicate of #387

**Comment by mikejbrown** [comment] 2016-09-16 15:44
@bjubes It's not an exact duplicate but yes, fair degree of overlap.

**Comment by bjubes** [comment] 2016-09-16 15:50
We already discussed multiplayer, despite this being a different implementation, its worth noting that we have already decided that multiplayer in the previous issue was too far of a goal to be working on currently

**Comment by TheAvaren** [comment] 2016-09-16 22:03
Well thank you all for your opinion's and answers, i know that this was not directly just a multiplayer question in fact i should of named the title after the other thing i wanted,i'm still watching the very early tutorials of this. should this issue be closed now.

**Closed** 2016-09-17 12:32 UTC
Labels: duplicate
