### ISSUE TITLE
Dynamic menu

### ISSUE THREAD

**Issue by vircung** [TeamPorcupine/ProjectPorcupine#668] opened 2016-08-23 09:43 UTC
I've started thinking on reworking build menu. In my opinion it should be code/items driven. Every item will have additional parameters like category or list of tags. And based on those categories/tags items will be places in proper spots in menu.  We could whitelist only those that can create higher level menu entries.

This would be also one of points where mod management #528 can be automated.

**Comment by koosemose** [comment] 2016-08-23 10:02
There was some discussion of this when I was first thinking about implementing BaseType (which became TypeTag), regarding using that as categorization, and once it transition to TypeTag (which can be multiples) using that and allowing things to be in multiple categories. That's still a possibility, though it would mean, in many cases, you may have super-specific categories (such as "door" and "wall").

**Comment by Fogsight** [comment] 2016-08-23 10:05
Great idea, if #666 go through, you would be able to `Resources.Load` prefabs as well. Less things hardcoded on the scene the better.

Probably some kind of centralized view-state-machine connected to menus would be beneficial as well.

**Comment by vircung** [comment] 2016-08-23 10:26
@koosemose having ```TypeTag``` already in place is good start with. This could correspond to skill needed to use/create that object.

For category data i thought it could be higher level like: structure, workshop, furniture, defense, utility, job, etc. And i found this one #324

**Comment by Fogsight** [comment] 2016-08-23 11:17
Also if UI is to be remade we should consider switching canvas to use Constant Physical Size to prevent #471. It would affect everything.

**Comment by longtomjr** [comment] 2016-09-20 12:08
Can we get the status on this please?

**Comment by TomMalbran** [comment] 2016-09-20 19:11
@longtomjr We are creating the content of the Construction Menu in code with all the Furnitures, Utilities, Tiles and the Deconstruct Buttons. And it has a filter field. We are missing the categories, and probably the ability to add items from outside menu (maybe for modding). And some polish on the UI.

**Comment by Jaytheway** [comment] 2016-09-27 17:46
There is a Bug in the Construction menu. When you hold scroll field (not the handle) and move mouse down it sometimes scrolls up and when you move the mouse up it scrolls down. It happens not all the time though.

**Comment by koosemose** [comment] 2016-09-28 12:23
@Jaytheway please report bugs in their own issue, they disappear too easily if added to an already existing issue (unless the issue is a bug report on the same bug), especially one that is old.

**Comment by koosemose** [comment] 2016-11-17 01:16
Closing this as implemented, further refinements can be proposed and handled in separate issues.

**Closed by koosemose** 2016-11-17 01:16 UTC
Labels: discussion
