### ISSUE TITLE
Make rooms aware of inventory

### ISSUE THREAD

**Issue by MattPotticary** [TeamPorcupine/ProjectPorcupine#950] opened 2016-08-27 12:16 UTC
I would like to change the way inventory is handled from globally to a room by room basis. This would be  a precursor to fixing searching for inventory by the character. 

It would be something like this

``` c#
PlaceInventory(Tile, Inventory)
{
tile.add.inventory( Inv );
tile.room.registerInventory(Inv, Tile);
}
```

and then in room there would be a dictionary of the inventory type and a list of tiles which contain it.

``` c#
AvaliableInventory = Dictionary<Inv, List<Tile>>;

Public void registerInventory(Inv, Tile)
{
AvaliableInventory[Inv].Add.(Tile);
}
```

What do people think?

**Comment by sboigelot** [comment] 2016-08-27 14:55
I had to fiddle around with the inventory system in order to find all items within stockpiles.

This is not merged yet but it looks like this


        List<List<Inventory>> worldInventories =
            WorldController.Instance.World.inventoryManager.inventories.Values.Select(i => i.ToList()).ToList();
        
        foreach (List<Inventory> worldInventory in worldInventories)
        {
            foreach (Inventory inventory in worldInventory)
            {
                if (inventory.tile != null && 
                    inventory.tile.Furniture != null &&
                    inventory.tile.Furniture.ObjectType == "Stockpile")
                {
                    t.Stock.Add(inventory);
                }
            }
        }

How would you achieve this if the rooms had their own inventory system. I know we can iterate over each rooms and do the same search... But maybe we can find a better way to index the inventories.

**Comment by mikejbrown** [comment] 2016-08-27 15:27
@sboigelot  All I would do in your code same is change the `ObjectType == "Stockpile"` to use the Furniture `HasType` method (if it's still there -- haven't looked in a while). That's more future proof because it reads from the xml furniture definitions.

Re your actual question: Is there any reason not to maintain global and per room lists at the same time? Then you could use whatever search strategy is easiest at the time.

**Comment by vogonistic** [comment] 2016-08-27 17:15
I'm not a fan of keeping a global list and a per-room list. Since we are about to have a room graph in #760, we should just rewrite the InventoryManager to start iterating over the connected rooms until it finds what we are looking for. All the current inventory searches always have a Tile, so it makes sense. Effectively, this gives you the same thing without duplicating the lists.

**Comment by mikejbrown** [comment] 2016-08-27 17:18
So "hold off." :+1: Can do. :smile:

**Comment by sboigelot** [comment] 2016-08-27 17:40
@mikejbrown yep that was my actual question. Let's keep a global index in addition to your changes

**Comment by mattpott** [comment] 2016-08-27 17:47
That was my plan for the future of searching was to check the current room for the inventory you are looking for. If that fails then check the neighbouring rooms and so on from out there. 

This would be in effort to stop searching the whole map for an inventory but I wanted to split the pull request so it is easier to merge.

**Comment by Fatalexceptionz** [comment] 2016-08-28 08:03
Yus, This can double as a rough first-pass for nearest-first searches, and combined with the room graph should substantially reduce the load on A*

**Comment by TomMalbran** [comment] 2016-08-28 08:17
It should be noted that is very posible that inventory in another room can be closer to the inventory in the room you are in. Is easy to imagine a situation where you are in a big room, you are in a corner next to a door, and there is the required inventory in the opposite side of the room, but there is also some required inventory on the adjacent room close to the door. It will then be faster to go to the adjacent room and pick that inventory than the one in the room you are in.

**Comment by mattpott** [comment] 2016-08-28 08:50
That could very well happen but you have to remember you also have the speed of opening and closing the door on both sides which would also add a second or two on to the time. 

That might also be ab edge case and the computational cost of checking that edge case may not be worth it.

**Comment by koosemose** [comment] 2016-11-17 01:22
While not an identical implementation #1612 seems to achieve much of what was suggested here, and reaches a result similar to what was intended (quicker searching for inventory)

**Closed by koosemose** 2016-11-17 01:22 UTC
Labels: enhancement
