### ISSUE TITLE
Character Naming should not be in CharacterSpriteController

### ISSUE THREAD

**Issue by quill18** [TeamPorcupine/ProjectPorcupine#513] opened 2016-08-21 13:55 UTC
`CharacterSpriteController.OnCharacterCreated()` is assigning characters random names.  This is interesting and fun, but the sprite controller is for controlling sprites -- not naming characters.

Additionally, the names are currently being read from a Text Asset (i.e. something in the unity asset bundle) and not from Streamed Assets. That means it isn't as modable.

**Consider a better place for this system.**   We should have a single, centralized place for creating/spawning a brand new character.  `World.CreateCharacter()` is used for that now, though maybe even that isn't the right place.  We could have a static function inside of Character.cs or make it part of the constructor, to keep all "Character" code in the same place. Or maybe you'd prefer a lean "CharacterSpawner" class that handles the setup, leaving Character.cs to concern itself with the operation of an *active* character only, rather than worry about spawning. It's up to you.

Whatever you decide, it should read in the list of character names from StreamingAssets, rather than from a resource file.  Maybe in the future we could use a name generator that just chains syllables together, rather than rely on a fixed list (or a combination of the two).

**Comment by fre-ber** [comment] 2016-08-21 14:06
How about a CharacterManager class that both provide a way to create and remove characters but also keep track of them, thus removing this responsibility from the World class?

However, I think that would be a separate issue though, as even that might not be the best place for a random name system. We might want to have random names for other things, not only characters, so maybe a spearate NameGenerator class with static methods for generating names for different things?

**Comment by Ceddini** [comment] 2016-08-21 14:58
I guess you're right. I thought about it, like in RimWorld, where there is no real access to the name files (at least that I know of). And I wanted it to be a little reward for being a contributor, because the names are all from the contributor. But I slept over the idea that it isn't accessible to others and I remembered a time, when I added my friends to Prison Architect... So I will definitly change it.

And the naming being done in the CharacterSpriteController() was because I didn't know a better place and because the names are only visible on screen and have no real meaning in code, I thought it might fit there.
Now my question is: Where is a better place to put it?, or is it okay to leave it in there for now, until we have a better way on handling the Characters?

But I am all for a NameGenerator system, but since I am new to Unity and to programming in c# in general I don't really now where to add it... Should it just be a Controller called "NameGeneratorController" or how would be best to tackle it?

**Comment by fre-ber** [comment] 2016-08-21 15:25
My first thoughts on this were to have a static class NameGenerator, maybe in Utilities, then let that class have a static function called something like Init(), this function would, when called, read in the file with names. In addition, the class would have another static method, GenerateRandomCharacterName or something like that. This would return a string with the new name.

Then, some class needs to call the Init method on game startup, possibly this should be done somewhere in the World class. And then whenever a new Character is created, as in the constructor(s) of the Character, a call to GenerateRandomCharacterName should be made.

Make sure to check the loading and saving of names though, you don't want it to overwrite the name loaded from a save game if one exists. 

Feel free to elaborate or do something completely different, though. :)

In the future we could change the behaviour of this class to run through some statistical algorithm to actually generate completely random names by combining common syllables, compare with the names in Stellaris, for example. I tried doing something like this to generate "Star Wars-looking" names for another project. It was fun, but the algorithm for that became a bit complicated.

**Comment by Ceddini** [comment] 2016-08-21 15:36
Okay, thank you! :D 
Now I know exactly what should be done. But I will still leave my PR up to fix it for now, until I have something better to show, or until someone made something better.

And the idea of completely random names sounds pretty interesting to me. I would love to see something like that implemented. Do you possibly know where I could find a good source on how to do something like that? I really don't want to implement it, but I still would love to learn more about that, because my main goal for now, is to bring the contributors into the game. Not only the usernames, but perhaps also the real names, if I can get them through the GitHub API.

**Comment by fre-ber** [comment] 2016-08-21 16:02
I based my old code on this https://github.com/gilles-leblanc/RandomNameGenerator but since I don't know ruby at all, it took me some time to understand how it works and I am still not 100% certain that my code does the right thing.

**Comment by Ceddini** [comment] 2016-08-21 16:23
Thank you very much! 😄 
I will read it as soon as I finish the NameGenerator.

I added the Init method to `WorldController.OnEnable()` because I didn't find a better place for it.
But I also added a AddName() and RemoveName() functionality to the NameGenerator and made it accessible from lua!

**Comment by fre-ber** [comment] 2016-08-21 16:25
Cool.

**Comment by kd7uiy** [comment] 2016-08-29 13:52
Is this complete?

**Comment by vogonistic** [comment] 2016-08-29 14:32
We only have names from contributors. We probably needs something fancier.

**Comment by kd7uiy** [comment] 2016-08-29 15:56
I think we should also add all donators from the Patreon page. I'm sure there's a fair bit of overlap, but why not? It might be better for @quill18 to weigh in on that first, however.

**Comment by kd7uiy** [comment] 2016-08-29 16:08
In any case, the names isn't the issue for this, rather, the location where the names are assigned. I've confirmed that it is indeed set in World.cs now, which is a reasonable place for it, so I suggest we close it. 

A better spot would probably be the Character class, but...

**Closed** 2016-08-29 16:30 UTC
Labels: discussion, for beginners
