### ISSUE TITLE
[Bug] Latest merge has bugs

### ISSUE THREAD

**Issue by satch3l** [TeamPorcupine/ProjectPorcupine#383] opened 2016-08-20 12:26 UTC
* Workers doesn't carry metal chunks to the smelter.
* Pathfinding test just adds walls on top of current world.
* Metal chunks spawn on walls.
* Random empty scroll list on the left. 
* Workers have no collision against eachother (more of a missing feature)

I guess there are more, but these are the ones that stood out to me.

**Comment by RodRitter** [comment] 2016-08-20 12:36
I've seen that AI don't actually get assigned to free jobs sometimes, but that's been an issue for a couple days now.

**Comment by koosemose** [comment] 2016-08-20 12:41
A quick test seems to have Workers carrying metal chunks to the smelter just fine, however, they only do so when it is empty, rather than keeping it topped off (presumably by design).

**Comment by quill18** [comment] 2016-08-20 12:57
What do we think about just removing the pathfinding test at this point?

**Comment by koosemose** [comment] 2016-08-20 12:59
I've used it to quickly set up a test for gasses, but that can be approximated just as well with a little bit of time setting up an appropriate save file.

**Comment by gunthergun** [comment] 2016-08-20 13:11
We should remove the pathfinding test and add some test save files that are copied in the save folder :)

**Comment by koosemose** [comment] 2016-08-20 13:13
Alternatively, or additionally, a dev-mode, that makes things instabuild could be very useful, especially for those times that pathfinding is acting up.

**Comment by gunthergun** [comment] 2016-08-20 13:14
Yeah that sounds nice as well

**Comment by FilippoLeon** [comment] 2016-08-20 13:17
Which will fix https://github.com/TeamPorcupine/ProjectPorcupine/issues/369

**Comment by Mizipzor** [comment] 2016-08-20 13:19
@FilippoLeon Are you sures its "fixed" by removing the path finding test? I created that issue with the intention to figure out how to correctly handle tests going forward. so that it scales and we can add more. Not remove.

**Comment by koosemose** [comment] 2016-08-20 13:20
If no one has implemented a dev mode by the time I next get free time for significant programming (Monday at the earliest), I'll look into implementing a dev-mode.

**Comment by bjubes** [comment] 2016-08-20 14:06
Could we also have a similar but separate "God Mode" where you can place any furniture you want with a click and spawn in materials too? or is this exactly what the debug mode would do?

**Comment by Mizipzor** [comment] 2016-08-20 14:08
I think you refer to the same thing when you say god mode and dev mode.

**Comment by koosemose** [comment] 2016-08-20 14:14
Same intent, I'd already mentioned the idea elsewhere as dev mode, so continued using that name. The initial pass on it will likely only include instaclick builds, as that's what I'm presently looking into, and think will be the easiest.

**Comment by koosemose** [comment] 2016-08-20 14:28
Ok, I lied, I've got a basic devmode implemented...

**Comment by kd7uiy** [comment] 2016-08-29 13:44
It seems really likely this is resolved.

**Comment by Mizipzor** [comment] 2016-08-29 13:46
Closing due to inactivity. Its a list of issues anyway, the correct thing to do is the create one issue for each problem.

**Closed by Mizipzor** 2016-08-29 13:46 UTC
Labels: bug
