### ISSUE TITLE
What should [WIP] imply about a PR?

### ISSUE THREAD

**Issue by abackwood** [TeamPorcupine/ProjectPorcupine#1148] opened 2016-09-05 06:29 UTC
Basically that.

I personally use it for three reasons:
1) Telling the gatekeepers to ignore it for now
2) Claiming that feature as mine so others dont go and make duplicates in the time it takes me to make it
3) Allowing people to give feedback on my specific implementation rather than an abstract concept in an issue

Only usage 1 is official. So how should I understand that tag?

**Comment by vogonistic** [comment] 2016-09-05 06:39
I think all 3 makes sense.

**Comment by dusho** [comment] 2016-09-05 06:41
by 1) does it mean that gatekeeper only ignores it for merge, right.. not for checking what is going on there

**Comment by vogonistic** [comment] 2016-09-05 06:44
In an ideal world, we would have time to review everything early. Right now, we can't keep up with the reviews on items that are ready to be merged.

**Comment by koosemose** [comment] 2016-09-05 06:46
1st one is of course obvious, and the second indirectly (Any PR sort of informs anyone that's looking at issues that you're working on a thing, a wip just lets you put it up before it's fully ready, so you don't have to wait til it's done).

The 3rd is similar to the second, in that any PR allows people to comment, and with WIP you just put it up early. However, there is another thing somewhat different but linked that I think we could use as a distinct pseudo tag convention. Something along the line's of [Request Feedback], rather than just a "Hey this is a thing I'm working on, it's up here to comment on if you want", more of a "I'd really like some thoughts and feedback on this feature/idea".

**Comment by abackwood** [comment] 2016-09-05 15:11
The problem with 2 and 3 is that i see that non-gatekeepers also tend to ignore WIP requests. If we want it to have that purpose we should really encourage people to look anyway and comment on the progress and ideas.

Koosemose, I like your idea for a feedback requested tag

**Comment by frankitox16** [comment] 2016-09-05 16:27
I think it also should involve someone else testing it, finding bugs or something like that before being merged, that way we avoid plenty of new bugs in the game.

**Comment by TomMalbran** [comment] 2016-09-05 20:07
For me [WIP] mainly means Working on this thing. But the issue is that if you don't say it in the description I can't be sure what you are working on, so something that I suggest, comment might be something that you were already planning to do. And i am not even sure about commenting on the code since it might change, unless I see something that could be done in a better way. But even if that is the case, you might have just made a prototype thing to see it working and were planning to make the code nicer later.

If you want feedback I would rather have a [Feedback] tag, which is more explicit, and mention in the description if the work is done and want just to know what others think before merging or what are your plans for the next things you will work with.

**Comment by bjubes** [comment] 2016-09-05 20:51
I assume WIP as: 
* don't test yet as it probably doesn't work as expected.
* Look at it because its probably a bigger change  that you need to know about in the future
* give general feedback on my implementation, but don't go nitpicking or stylechecking yet

**Comment by bjubes** [comment] 2016-10-05 16:32
closing due to general consensus. I haven't seen any unclear uses in the past month since this was opened

**Closed by bjubes** 2016-10-05 16:32 UTC
Labels: question
