### ISSUE TITLE
Build categories for furniture

### ISSUE THREAD

**Issue by dusho** [TeamPorcupine/ProjectPorcupine#1254] opened 2016-09-10 19:32 UTC
It's starting to get messy in construction menu and I think it's time for build categories.
Currently there is 
* Construction
 * Furniture
 * Floor
 * Deconstruct Furniture

![image](https://cloud.githubusercontent.com/assets/12616499/18413029/72869524-779d-11e6-9404-0eb7ba540b51.png)
Let's have another tag for furniture:
`<BuildCategory></BuildCategory>`
So e.g. RTG:
`<BuildCategory>Power\Generators</BuildCategory>`
or table
`<BuildCategory>Furniture\Dinning</BuildCategory>`
UI should be also dynamically created using those categories as submenus for now.. 
Does it make sense?

**Comment by bjubes** [comment] 2016-09-10 20:29
duplicate of #978

**Comment by dusho** [comment] 2016-09-10 21:10
ups.. sorry.. didn't see that
guess you can close this...

**Closed** 2016-09-10 21:21 UTC
