### ISSUE TITLE
TravisCI builds

### ISSUE THREAD

**Issue by ulve** [TeamPorcupine/ProjectPorcupine#73] opened 2016-08-17 15:51 UTC
Is there any posibility to enable unity cloud build for this project. A up to date build status and a built package to download would be great!

**Comment by svmnotn** [comment] 2016-08-17 17:51
I would also want to know if unity cloud build has any support for github integration or if it only talks to unity stuff. Because that would allow all PRs to be checked to see if they still build.

**Comment by ulve** [comment] 2016-08-17 17:55
It has github integration and can build to multiple targets. It also has slack integration as well as webhooks. 

I did a test run and the 32 bit windows build is working. Have not tried any more features though.

**Comment by bjubes** [comment] 2016-08-17 18:05
I know that it will build the master branch, but pr might require some custom logic

**Comment by ulve** [comment] 2016-08-17 18:07
I can look in to a travis CI build script.

**Comment by ulve** [comment] 2016-08-17 19:44
Seems to be working for a mac build:
https://travis-ci.org/ulve/ProjectPorcupine

Most of whats done is taken from https://github.com/JonathanPorta/ci-build

Things that can (and some must) be fixed:
- [ ] Enable linux and windows builds. Might be a compilation flag problem but after compilation I get the following error: `Building a player for 'Win' (5) target is not supported in this Unity build.`
- [ ] Push build artifacts somewhere (perhaps)
- [ ] Download latest version of unity (perhaps)
- [ ] Make sure the build is ok for real, i have not tested the build artifacts 
- [ ] ensure exitcodes from the builds is working correctly

I will be out of town until monday so I have no time to fix anything before then. Feel free to take my scripts and travis config and run with it. https://github.com/ulve/ProjectPorcupine/

**Comment by ulve** [comment] 2016-08-17 20:00
OK spamming here :) 

The problem with building windows and linux versions is the following:
singe 5.3 the modules for each architecture must be installed separatly. I have no idea how to do this from the commandline but I have a macbook somewhere so I can try to figure it out later if someone don't already know how.

**Comment by svmnotn** [comment] 2016-08-17 21:10
@ulve did yiu try having a pr built using unity cloud?

**Comment by bjubes** [comment] 2016-08-17 21:55
Without unit tests as well, CI may not be very useful on PR. It will likely save a few bad PRs from having to be checked since they don't even compile, but won't most problems in PRs lie within runtime errors and bad functionality?

**Comment by svmnotn** [comment] 2016-08-17 23:14
Yes, that is something that should be looked into as well, however I'm not entirely sure how to write proper unit tests for a video game. Thus I think that bit might be placed on the bottom of the TODO list.

**Comment by vogonistic** [comment] 2016-08-17 23:18
Not sure how well the current controllers work with the integration tests included, but Unity does have an official asset package that helps you do both unit and integration tests.

https://unity3d.com/learn/tutorials/topics/production/unity-test-tools

**Comment by sboigelot** [comment] 2016-08-22 18:09
cf: #578

**Comment by Mizipzor** [comment] 2016-08-22 19:03
Its been five days so I [gave it a shot](https://travis-ci.org/Mizipzor/ProjectPorcupine). But cant really get it to work.

**Comment by Mizipzor** [comment] 2016-08-22 20:02
The problem is that the solution file is not checked in. So for Travis to be able to do something, a solution file must be generated. I found [this](https://github.com/malud/unity-solution) that could generate the solution file. But it seems to be for an old version or something because [build 12](https://travis-ci.org/Mizipzor/ProjectPorcupine/builds/154253074) complain about missing **Dropdown**. I dont know why. Ill keep my [branch](https://github.com/Mizipzor/ProjectPorcupine/tree/travis), but ill give up for now.

**Comment by ulve** [comment] 2016-08-22 20:05
I got it to build the macos version. Tried to downgrade unity and build with a version that includes all the different architectures but failed. Still out of town so I cant fix anything now. at the moment my solution might be broken since it downloads the older version and times out.

**Comment by Mizipzor** [comment] 2016-08-22 20:07
@ulve Great. For the record, I would really like to see this happen. :)

**Comment by Mizipzor** [comment] 2016-08-22 20:08
Hm. Im missing a label for this. Build? Automation?

**Comment by ulve** [comment] 2016-08-22 20:09
https://travis-ci.org/ulve/ProjectPorcupine/builds/153073773 think that commit actually built the macos version. But as I said, I cant figure out how to install the modules for windows and linux.

**Comment by Mizipzor** [comment] 2016-08-22 20:26
I suppose I dont care. My primary goal was to make sure that we dont spend time on pull requests that dont compile. But of course for the future we want it to provide binaries for the game as well as running stylecop.

**Comment by vogonistic** [comment] 2016-08-24 15:18
What do we do about this? I think it would be a huge benefit to the project.

**Comment by Mizipzor** [comment] 2016-08-24 18:35
@vogonistic I still *really* want this to happen. But I havent found the time yet, the time Ive had has gone to pull requests. My branch and all that is still there (linked above).

**Comment by vogonistic** [comment] 2016-08-24 18:36
My time is also almost entirely devoted to PR's. Maybe we can find someone else to take it on.

**Comment by bjubes** [comment] 2016-08-24 20:47
Is there any tools that allow stylecop to auto check PRs? I googled for a bit but found nothing. CI would be great but I would prefer to have unit tests over simple compilation since most errors in PRs thus far break previous logic on runtime not when compiled

**Comment by Mizipzor** [comment] 2016-08-24 20:56
For me, the biggest problem was that the solution file needs to be generated by something. One approach was to install the editor on the build machine, dont ask me how they allow this. Another approach was a custom tool that generated a solution, also linked above. Neither worked. I suppose if we can live with having a solution file checked in, thats the quickest dirtiest way to get something running.

**Comment by Mizipzor** [comment] 2016-08-24 20:57
@bjubes Yes, StyleCop can be ran as part of MsBuild, so if we get some kind of CI system going, thats the obvious next step.

**Comment by vogonistic** [comment] 2016-08-24 20:59
If we can figure out the command, getting a CI system to run is trivial. After that it gets a bit more complicated because it needs rights to change the status of the PR, which means admin rights.

**Comment by vogonistic** [comment] 2016-08-25 06:47
Alright, I've merged #773, so we actually have some NUnit tests in the project. Here is how you run them from a cli inside the ProjectPorcupine on a Mac (with Unity.app shut down): `/Applications/Unity/Unity.app/Contents/MacOS/Unity -batchmode -runEditorTests -quit -projectPath $PWD`

**Comment by Mizipzor** [comment] 2016-08-25 08:18
@vogonistic Assuming we go with Travis it need no additional permission to change the status of a pull request. They are automatically built and a result is visible below the pull request where we currently see merge conflicts. So its not part of the pull requests state. Neither the author nor gatekeepers need to explicitly kick off a build or collect the results. This is due to Github intergrating with Travis explicitly. 

Unless I misunderstood you completely. :)

**Comment by sboigelot** [comment] 2016-08-25 12:30
@Mizipzor you didn't misunderstood, it really work like that

**Comment by vogonistic** [comment] 2016-08-25 22:03
That doesn't sound right. It'd be a problem if anyone with API knowledge is allowed to change the status of a PR. It'd have to be given an access key to the repo in some way. I mean, if you make make it work without, you'd blow my mind and I would report a bug to github because it'd break protected branch status at the very least.

**Comment by Skalicon** [comment] 2016-08-31 02:01
Vogonistic, you are right, there is an account linking between Travis and Unity Cloud build that enables our permissions, this can be done without giving away details to the admin account.

Regarding building, we should not be attempting to build the project ourselves with a CI, this is pointless when we have Unity Cloud Build. We can use their API service to build any projects we like with error checking and any PRE or POST build scripting we like which would enable us to run unit tests after build.

API: https://build-api.cloud.unity3d.com/docs/1.0.0/index.html
Create a Unity Cloud Build account with an admin Git account.

Setup:
1. Create a Travis or other CI tool account.
2. Create a build that triggers on PR into develop branch

Build process:
1. CI tool builds Project
2. Unity Cloud Build API  - Create new Cloud Build project for https://github.com/TeamPorcupine/ProjectPorcupine
3. Unity Cloud Build API  - Add a new build target for each supported environment for the PR branch on the cloud build project //Add unit tests to post build scripts
4. Unity Cloud Build API  - Build all build targets for build project
5. Unity Cloud Build API  - Check API return for errors
6. Unity Cloud Build API  - Remove Cloud Build project
7. Fail or succeed build based on Cloud Build API return
8. PR Automatically notified of build status

Requirements:
This does require that we are setup to use a single repository since Unity Cloud Build does not have access to the forks where the code that requires testing lives due to them being on the users personal github account. I have a post discussing this implementation here  #1054. We do not need to have CI before implementing this change.

I am happy to start working on this now, I can get started on the 2nd of Sept.

**Comment by bjubes** [comment] 2016-08-31 02:28
So to clarify, your plan will allow us to automatically build PRs and run tests on them? Or just build and test the master and develop branches?

**Comment by bjubes** [comment] 2016-08-31 02:30
Also there has to be a way to make this work using the fork-PR model. I know that non unity projects do it and that it is possible according to unite 2015

**Comment by Skalicon** [comment] 2016-08-31 02:30
Build and test PRs.

**Comment by Skalicon** [comment] 2016-08-31 02:32
I will continue to investigate making this work with forked PRs, I have already figured out a way of making it work with a custom merge tool but there may be a simpler solution.

**Comment by vogonistic** [comment] 2016-08-31 02:54
Cloud builds are great for making builds from a stable branch, but the free option is much too slow for us to use for CI and statuses. 

What we need is a Travis build, triggered on PRs which is default config, and initially at least runs out unit tests, but ideally later runs stylecop too. This one we want to run on every PR as a test they must pass for us to merge.

**Comment by Skalicon** [comment] 2016-08-31 03:00
@vogonistic I agree, if we remove the requirement of building on PR then that reduces the complexity significantly.

Additionally, Unity Cloud build is really simple for us to implement as part of the release cycle

**Comment by vogonistic** [comment] 2016-08-31 03:36
Maybe I wasn't clear, we need something that builds each PR and will tell us that there are no compilation errors and that the unit tests pass. I don't want to involve the unity cloud build the way it was described in your earlier commit because they have a pretty long waiting time for the free level. If travis doesn't work for us, then lets find another CI that will do it, but I'm pretty sure we can make it work and they have no problems operating on PRs.

This is tangental, but we will add a stable branch later when there is an actual need for it. We are currently pre 0.1 milestone, there isn't much to consider stable yet. I already have cloud build setup to build off master, but it doesn't have any real value yet and it's not a 0.1 item. We'll probably enable it pretty quickly after 0.1 though.

**Comment by Skalicon** [comment] 2016-08-31 05:40
I deleted my comments to clear up the discussion on this topic. After chatting with @vogonistic we have decided that it is better to implement unity build testing through a custom installation of Unity that is created in the Travis CI build. I'll get started working on this and let you know how I go.

**Comment by bjubes** [comment] 2016-08-31 18:06
I have made a branch that uses unity build pipeline it attempt to do something similar with CI. When I get a chance I'll make a PR.

**Comment by Skalicon** [comment] 2016-08-31 23:10
I'm not sure if we can use this build pipeline, since the actual CI build in Travis runs on a Ubuntu VM, but this is helpful for people who want to test best their client before making a PR to check they didn't break any of the other OS distributions.

**Comment by vogonistic** [comment] 2016-08-31 23:32
There are 4 available environments and OSX is pretty well supported by Unity. It's what I use.

**Comment by bjubes** [comment] 2016-09-01 00:00
I'm pretty sure the build pipeline is the same for all platforms you run it on, the only thing that changes is the command used to start it.

**Comment by bjubes** [comment] 2016-09-04 02:11
#1094 has merged, this should be closed @vogonistic

**Closed** 2016-09-04 02:59 UTC
