### ISSUE TITLE
Make CanReplaceFurniture in XML consistent with TypeTags

### ISSUE THREAD

**Issue by lameox** [TeamPorcupine/ProjectPorcupine#1086] opened 2016-09-02 10:56 UTC
Currently the TypeTags implemented in #342 are defined as values of tags in the xml file. 

``` Xml
<TypeTag>Furniture</TypeTag>
<TypeTag>Storage</TypeTag>
```

however the CanReplaceFurniture Tags are implemented as attributes of tags, like 

``` xml
<CanReplaceFurniture typeTag="Furniture" />
<CanReplaceFurniture typeTag="Storage" />
```

I feel we should decide on one of the two ways and use them for both. Personally i would prefer the tag values aka the first approach.
I think this would be a good task for beginners as it is nothing urgent and should be a simple implementation change.

**Comment by koosemose** [comment] 2016-09-02 11:11
I'm not to sure about that, the actual Tags are defining what the furniture as a whole is, whereas the typeTag in the second is supplementary to CanReplaceFurniture...

**Comment by lameox** [comment] 2016-09-02 11:25
We could do a simple 
```xml
<CanReplaceFurniture />
```
if we want to replace any furniture and
```xml
<CanReplaceFurniture>
    <TypeTag>Furniture</TypeTag>
    <TypeTag>Storage</TypeTag>
</CanReplaceFurniture>
```
if we want to specify specific types

**Comment by mikejbrown** [comment] 2016-09-26 21:00
Any reason to keep this open?

**Comment by lameox** [comment] 2016-09-28 07:41
Well i guess since there was not much discussion and no approval or attempts at implementation we can close it

**Comment by sboigelot** [comment] 2016-09-28 08:14
@lameox I think many of us would have take the issue and fix it woudn't it be for the "for beginners" tag. As we decided to leave it for beginners. But obviously that tag doesn't work :)

If the issue is still in the code and.... checking.... yes it is, there is no reason to close it. It's not because no-one fixed it yet that the issue doesn't matter anymore.

**Comment by lameox** [comment] 2016-09-28 08:30
well in that case we should at least remove the for beginners tag so people don't feel like ignoring it

**Comment by sboigelot** [comment] 2016-09-28 08:31
done :)

**Closed** 2016-12-01 09:24 UTC
Labels: enhancement
