### ISSUE TITLE
Current master is broken? Localization issue

### ISSUE THREAD

**Issue by RodRitter** [TeamPorcupine/ProjectPorcupine#171] opened 2016-08-18 16:34 UTC
Hey guys, I know there was an issue before regarding the build menu and I saw this was getting fixed, but I see that there have been multiple commits since then so it might just be me.

This has something to do with the Localization change. I don't have any furniture in my build menu:

```
NullReferenceException: Object reference not set to an instance of an object
FurnitureBuildMenu.Start () (at Assets/Scripts/UI/FurnitureBuildMenu.cs:34)
```

`go.transform.GetComponentInChildren<TextLocalizer>().formatValues = new string[] { LocalizationTable.GetLocalization(World.current.furniturePrototypes[s].localizationCode) };`

**Comment by Mizipzor** [comment] 2016-08-18 16:43
I believe this was fixed by #154. Try latest master.

**Comment by RodRitter** [comment] 2016-08-18 16:44
I have that already. I'm on latest.
![image](https://cloud.githubusercontent.com/assets/4159679/17782434/bec9d400-6573-11e6-91d5-393220afd62c.png)

**Comment by Mizipzor** [comment] 2016-08-18 16:47
Then I'm confused. Why am I not seeing the error in my log?

**Comment by SanteriHetekivi** [comment] 2016-08-18 16:52
Maybe different Unity versions?
Some of the issues have been fixed by updating Unity to 5.4.
I'm not at my main PC right now so can't check, but when I did #169 build menu worked fine.

**Comment by RodRitter** [comment] 2016-08-18 16:53
I'll try an update to 5.4 and see. Thanks

**Comment by Mizipzor** [comment] 2016-08-18 16:55
Its sad that the line is rather long, so the null reference exception might happen in many places. Try split the line up?


	var localizer = go.transform.GetComponentInChildren<TextLocalizer>();
	var code = World.current.furniturePrototypes[s].localizationCode;
	localizer.formatValues = new string[] { LocalizationTable.GetLocalization(code) };

**Comment by relinu** [comment] 2016-08-18 17:01
The only way for me to reproduce this error is by removing the TextLocalizer from the Build Furniture prefab. And that should not happen :/

**Comment by NogginBops** [comment] 2016-08-18 17:06
This is fixed with 5.4, the problem is the button prefabs not working in 5.3. When I removed the spaces from the prefab name it suddenly started to work.

**Comment by RodRitter** [comment] 2016-08-18 17:07
Perfect, updating now. Thanks for your help guys.

**Comment by Mizipzor** [comment] 2016-08-18 17:08
@RodRitter Time to close this then? :)

**Closed** 2016-08-18 17:11 UTC
