### ISSUE TITLE
[Discussion] Game design document & planning

### ISSUE THREAD

**Issue by RodRitter** [TeamPorcupine/ProjectPorcupine#373] opened 2016-08-20 10:36 UTC
Hello everyone!

We have had amazing contributions into the project so far and some very innovative features have come out of it. The one problem I feel we're facing though, is that we have no goal or idea to base new features on. So I would like to propose a discussion around game mechanics and actual medium to long term goals that we would like to accomplish. This way we can shape new features with those goals in mind.

Hopefully we can create a design document on the Wiki that will help us with this. Any feedback is welcome.

**Comment by JosephBywater** [comment] 2016-08-20 10:49
There's one on the wiki already ;)

**Comment by koosemose** [comment] 2016-08-20 10:53
As much as I enjoy the wild and free "do your own thing" sort of feel we have going on, I really think we need some form of governing body, or at least some kind of voting system to approximate the same effect. We have a good 40 contributors, and I have no idea how many others involved in discussions. We've had several similar discussions both for a broad plan and more focused work on existing systems, and while we seem to have had some degree of success on the more focused work, the broader plan discussions seem to all fade away with no clear plan really even hinted at.

A governing body of maybe 5 or so people could take all the assorted suggestions for direction and much more easily decide which is in and which is out, then start plugging in the systems that are being discussed and plug those in where needed, and say "Hey, for this system to work we need someone to get on X". There'd still be room for people to propose ideas that may not directly match the plan to see if the governing body thinks it can be fit in and will be good for the overall project.

**Comment by satch3l** [comment] 2016-08-20 11:12
Maybe not a governing body but rather a design group that can establish the framwork of a design document with which we will work towards. Then of course I'd like to see more moderating people that can ease some of the workload off of Quill, which will hopefully speed up the development.

**Comment by Mizipzor** [comment] 2016-08-20 11:25
If youre tired of me constantly bickering about code style I want you to know that I'm not that concerned about the actual gameplay. I'm here for the code. ^^

**Comment by RodRitter** [comment] 2016-08-20 11:29
Moderation is another topic that Quill is trying to work out. But with regards to an actual game design, if @quill18 wants the community to guide the game mechanics and design, then we need to find some sort of voting mechanism.

**Comment by koosemose** [comment] 2016-08-20 11:42
Should we vote on the voting mechanism? ;D

**Comment by TheRiven** [comment] 2016-08-20 11:52
I definitely think fleshing out the Design Docs so that they show what the first.. milestone? of the game should be, what core features we should have by then and how those features should more or less work.

This would might help focus development a bit? 

Maybe also showing what the current state of play is and how/what features are working so you can get  a broad overview of the current state of the project?

**Comment by Mizipzor** [comment] 2016-08-20 11:52
I vote _for_ voting on the voting mechanism.

**Comment by TheRiven** [comment] 2016-08-20 11:54
@Mizipzor Have we determined how the voting process for the vote to vote on the voting mechanism will work yet? :smile:

**Comment by RodRitter** [comment] 2016-08-20 11:57
That's awesome! Love the humor

**Comment by bjubes** [comment] 2016-08-20 12:06
we could vote by having an issue and people either reacting thumbs up or down

**Comment by RodRitter** [comment] 2016-08-20 12:08
Maybe we can have a specific VOTING tag on voting issues.

**Comment by WardBenjamin** [comment] 2016-08-20 12:13
Yeah, that's definitely an idea. That's not really the most *secure* way to vote since I'm sure we'll get non-contributors voting, but honestly it's the best idea so far.

**Comment by koosemose** [comment] 2016-08-20 12:15
Is allowing non-contributors to vote an undesirable thing?

**Comment by RodRitter** [comment] 2016-08-20 12:15
Eh I don't think it matters. It's the community voting on ideas, not just contributors :)

**Comment by Mizipzor** [comment] 2016-08-20 12:20
The thumbs up or down on a post is a great way to vote that Ive seen used elsewhere. Especially stuff that maybe isnt _that_ important. Like that StyleCop issue I made asking for feedback.

But speaking of label, I want to see more of them! Lots of issues unlabeled,

**Comment by WardBenjamin** [comment] 2016-08-20 12:23
Agreed. Right now @vogonistic  and @RodRitter are our only "gatekeepers", and them and Quill are the only ones who can add labels. I've also been added to the TeamPorcupine organization but I don't have any permissions so /shrug

**Comment by Mizipzor** [comment] 2016-08-20 12:24
I wonder if theres a way to add permission to _only_ label issues.

**Comment by RodRitter** [comment] 2016-08-20 12:30
Github permissions are sparse so I doubt it. But maybe Quill can take submitted issues and add the ones he likes as voting issues. That means there's not too much work on his part but he can still guide the game.

**Comment by quill18** [comment] 2016-08-20 12:53
Basically, what we need is something like Issues, but with obvious and visible up/down vote tallies.  Ideally with a limited number of active votes per user so people have to prioritize.

Basically I'm asking if anyone know of something like Uservoice (https://www.uservoice.com/product/product-management/) but free?

**Comment by Mizipzor** [comment] 2016-08-20 12:57
I know the Mantis bug tracker includes a voting system (more granular than just up or down) but are we really going down the route of setting up a separate tracker? Maybe it is needed if the issue chaos continues,

**Comment by RodRitter** [comment] 2016-08-20 13:01
Maybe something like this? http://feathub.com/

**Comment by WardBenjamin** [comment] 2016-08-20 13:55
@RodRitter I'm a *huge* fan of that, looks like a much better system!

**Comment by quill18** [comment] 2016-08-20 14:02
@RodRitter That's exactly what I want!

Just set it up:
[![Feature Requests](http://feathub.com/TeamPorcupine/ProjectPorcupine?format=svg)](http://feathub.com/TeamPorcupine/ProjectPorcupine)

**Comment by quill18** [comment] 2016-08-20 14:08
Can you confirm that you guys can also create new requests (and vote)?

**Comment by Mizipzor** [comment] 2016-08-20 14:09
@quill18 I can confirm that I can create and vote.

**Comment by RodRitter** [comment] 2016-08-20 14:11
Yep, it all works as expected.

**Comment by quill18** [comment] 2016-08-20 14:12
Made a PR #392 to integrate into the README

**Comment by quill18** [comment] 2016-08-20 14:33
I say we wait a period of time (a week?) to shake out these initial very rapid PR's and let the votes trickle in, then we make a pass through the voting, considering priority + ease of implementation, and then create a milestone for "Version 0.1".

This would then be followed by making a new branch organization for the project to distinguish between things that are meant for version 0.1, and features that are more experimental (though if one of those features turns out to be good, stable, and easy to integrate, we could pull that in to the 0.1 branch).

**Comment by bjubes** [comment] 2016-08-20 14:37
Maybe when we have voted fully on the best features, we can order them and assign them on Trello, making a sort of feature map for said version 0.1

**Comment by Mizipzor** [comment] 2016-08-20 14:38
I dont think we need Trello as well. Lets take the voted stuff and create github issues from them, those can be assigned just fine.

**Comment by RodRitter** [comment] 2016-08-20 14:49
Github has a milestones feature that we can use. No need for another third party platform.

**Comment by WardBenjamin** [comment] 2016-08-20 17:46
Looks like we're going to use this! Closing!

**Closed by WardBenjamin** 2016-08-20 17:46 UTC
Labels: feedback requested
